export type DebtType = {
  parentGUID: string;
  debt: string;
  debtDate: string;
  orderNum: string;
  userName: string;
  dayOfYear: number;
  status: string;
};
export type PaymentType = {
  ID: number;
  price: string;
  dueDate: string;
  serial: string;
  seri: string;
  parentGUID: string;
  itemGUID: string;
  Title: string;
  status: string;
  agentDescription: string;
  agentUnconfirmReason: string;
  treasuryConfirmDescription: string;
  treasuryUnconfirmReason: string;
  dayOfYear: string;
};

export type SayadiResultType = {
  iban: string;
  issuedDate: string;
  expirationDate: string;
  serialNo: string;
  seriesNo: string;
  mediaType: string;
  branchCode: string;
  name: string;
  returnedCheques: null | string;
};

export type CheckColor = {
  chequeColor: string;
};

export type CustomerType = {
  Id: number;
  ID: number;
  Title: string;
  CustomerBrandName: string;
  CustomerCode: string;
  CUstomerType: string;
  City: string;
  State: string;
  Mobile: string;
  Phone: string;
  PostalCode: string;
  NationalNumber: string;
  Email: string | null;
  WebSite: string | null;
  OfficeAddress: string | null;
  FactoryAddress: string | null;
  Introduction: string | null;
  Legal: boolean;
  Genuine: boolean;
  Shop: string | null;
  CarCategory: boolean;
  NonCarCategory: boolean;
  Car_Coef: number | null;
  Carcategory_Code: string | null;
  Rateinfo: string | null;
  PurchaseProcedure: string | null;
  RelatedPeople: string | null;
  Representationrequest: boolean;
  SalesExpert: string;
  SalesExpertMobile: string;
  SalesExpertAcunt: string | null;
  SalesExpertAcunt_text: string;
  SupportExpert: string;
  SupportExpertAcunt: string | null;
  SupportExpertAcunt_text: string;
  UserName: string;
  Permision: string;
  Permision2: string;
  Date: string | null;
  Created: string;
  Modified: string;
  EditorId: number;
  AuthorId: number;
  guid_form: string;
  GUID: string;
  last_status_info: string;
  last_Discript: string;
  last_Date_Info: string;
  Updated: boolean;
  namayandegi: boolean;
  namayandegi_k: string;
  darsadinfo: string | null;
  group_mahsol_1: string | null;
  group_mahsol_2: string | null;
  adresshaml: string | null;
  telephonhaml: string | null;
  RegCode: string | null;
  EconomicNumber: string | null;
  Label: string | null;
  Persenal: string | null;
  OData__UIVersionString: string;
  OData__x062a__x063a__x06cc__x06cc__x06: number;
  ContentTypeId: string;
  FileSystemObjectType: number;
};
